### ISSUE TITLE
能支持扫描hive吗？以及图形化的web页面么？

### ISSUE THREAD

**Issue by 4everzain** [LianjiaTech/d18n#10]
能否支持图形化的配置页面，及扫描脱敏hive库么？感谢！

**Comment by martianzhang** [comment]
>能否支持图形化的配置页面

每家公司都有自己的数据治理平台，为 d18n 搭一个图形化界面风格也很难和大家自己公司的平台风格一致。

如果您这边缺少前端开发支持，有一个相对取巧的作法可以推荐给您。即：配置定时任务，将 d18n 输出的 json 巡检结果写入数据库，然后通过 Grafana 查询数据库展示巡检结果。

> 扫描脱敏hive库

搜到这个 Go 语言驱动，需要测试一下，如果这个驱动已经相对比较完善了那支持 Hive SQL 就没有任何障碍了。
https://github.com/sql-machine-learning/gohive
