### ISSUE TITLE
是否支持JSON数据脱敏

### ISSUE THREAD

**Issue by ninglianjie** [LianjiaTech/d18n#11]
请问，是否支持JSON格式的数据脱敏。比如data
`{"Userinfo":
    {"Firstname":x,
    "Lastname": y,
    "Password": *}
}`

**Comment by martianzhang** [comment]
数据库导出后的数据格式如果选 JSON 是可以存储脱敏之后的数据的。如果您想表达的是直接对一个 JSON 文件内容进行脱敏目前 d18n 还做不到。
