### ISSUE TITLE
请问支持复杂的查询语句吗

### ISSUE THREAD

**Issue by lovepeacee** [LianjiaTech/d18n#4]
如题，请问怎么和Java配合使用呢。有暴露的接口嘛。还是只有命令行

**Comment by martianzhang** [comment]
> 请问支持复杂的查询语句吗

只要是对应数据库支持的查询语句，d18n 直接转发给对应的数据库执行，然后把结果保存文件。
按输出的字段名配置好脱敏规则，输出的结果就是脱敏的了。

> 请问怎么和Java配合使用呢

如果您使用的是 go 语言可以包引用，如果是其他语言建议调用系统调用命令行工具
